User.create!(name: "admin", email: "admin@test.com", password: "12345678", password_digest: "12345678", gender: 'Male', level: "Admin")
User.create!(name: "user1", email: "user1@test.com", password: "12345678", password_digest: "12345678", gender: 'Male', level: "1")
User.create!(name: "user2", email: "user2@test.com", password: "12345678", password_digest: "12345678", gender: 'Male', level: "2")
User.create!(name: "user3", email: "user3@test.com", password: "12345678", password_digest: "12345678", gender: 'Male', level: "3")

(1..3).each do |t|
	first_exam = Exam.create!(position: (1+t), title: "First exam for level #{t}", level: t.to_s, video: "https://www.youtube.com/watch?v=g6p7eTejWRY", comment: "Comment for first exam level #{t}")
	second_exam = Exam.create!(position: (2+t), title: "Second exam for level #{t}", level: t.to_s, video: "https://www.youtube.com/watch?v=g6p7eTejWRY", comment: "Comment for second exam level #{t}")
	first_question_first_exam = Question.create!(title: "First question for first exam level #{t}", exam_id: first_exam.id)
	Answer.create!(question_id: first_question_first_exam.id, title: 'Answer 1', right: '0')
	Answer.create!(question_id: first_question_first_exam.id, title: 'Answer 2', right: '0')
	Answer.create!(question_id: first_question_first_exam.id, title: 'Answer 3', right: '1')
	Answer.create!(question_id: first_question_first_exam.id, title: 'Answer 4', right: '0')
	second_question_first_exam = Question.create!(title: "Second question for first exam level #{t}", exam_id: first_exam.id)
	Answer.create!(question_id: second_question_first_exam.id, title: 'Answer 1', right: '0')
	Answer.create!(question_id: second_question_first_exam.id, title: 'Answer 2', right: '0')
	Answer.create!(question_id: second_question_first_exam.id, title: 'Answer 3', right: '1')
	Answer.create!(question_id: second_question_first_exam.id, title: 'Answer 4', right: '0')
	first_question_second_exam = Question.create!(title: "First question for second exam level #{t}", exam_id: second_exam.id)
	Answer.create!(question_id: first_question_second_exam.id, title: 'Answer 1', right: '0')
	Answer.create!(question_id: first_question_second_exam.id, title: 'Answer 2', right: '0')
	Answer.create!(question_id: first_question_second_exam.id, title: 'Answer 3', right: '1')
	Answer.create!(question_id: first_question_second_exam.id, title: 'Answer 4', right: '0')
	second_question_second_exam = Question.create!(title: "Second question for second exam level #{t}", exam_id: second_exam.id)
	Answer.create!(question_id: second_question_second_exam.id, title: 'Answer 1', right: '0')
	Answer.create!(question_id: second_question_second_exam.id, title: 'Answer 2', right: '0')
	Answer.create!(question_id: second_question_second_exam.id, title: 'Answer 3', right: '1')
	Answer.create!(question_id: second_question_second_exam.id, title: 'Answer 4', right: '0')
end